In [1]:
import torch 
import numpy as np

In [4]:
# 打印cuda设备, 即显卡名字
torch.cuda.get_device_name(0)

AssertionError: Torch not compiled with CUDA enabled

In [5]:
print(torch.cuda.is_available())

False


# pytorch张量

-pytorch中的张量和tensorflow的tensor是一样, 名字都一样. 

-pytorch中的张量也叫tensor

-tensor和numpy中的ndarray也是一个意思. 只不过tensor可以在GPU上加速计算.

## 创建tensor

In [6]:
# 创建tensor
torch.tensor([6, 2], dtype=torch.int32)

tensor([6, 2], dtype=torch.int32)

In [7]:
torch.tensor((6, 2))

tensor([6, 2])

In [8]:
torch.tensor(np.array([8, 10]))

tensor([ 8, 10], dtype=torch.int32)

In [9]:
# 快速创建tensor的方法. 和numpy中的routines方法一样. 
# ones, zeros, full, eye, random.randn, random.normal...arange...random.rand, random.random
# 创建一个0到1之间的随机数组成的tensor
torch.rand(2, 3)
torch.rand((2, 3))

tensor([[0.9900, 0.0268, 0.1239],
        [0.0938, 0.0461, 0.4279]])

In [10]:
# 标准正态分布
torch.randn(2, 3)

tensor([[ 1.0018,  0.0474, -0.3836],
        [ 0.9759,  0.0593, -0.9167]])

In [11]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [12]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [13]:
# tensor的shape
x = torch.ones(2, 3, 4)
x.shape

torch.Size([2, 3, 4])

In [14]:
# 可以通过.size()方法获取形状
x.size()

torch.Size([2, 3, 4])

In [16]:
# size中可以传shape的索引
x.size(2)

4

In [17]:
x.size(0)

2

# tensor中的基础数据类型

- 32位浮点数: torch.float32
- 64位浮点数: torch.float64
- 32整数: torch.int32
- 16整数: torch.int16
- 64整数: torch.int64

In [19]:
# 我们可以在创建tensor时候指定数据类型
torch.tensor([6, 2], dtype=torch.float32)

tensor([6., 2.])

tensorflow不能直接用tensor方法来创建tensor

tensorflow提供了constant, Variable 

keras: deeplearning for human

In [20]:
# tensor和ndarray很方便的进行转化
n = np.random.randn(2, 3)
n

array([[ 1.47794424, -0.29524533, -1.44897026],
       [-0.11100034,  0.3654316 , -1.11984385]])

In [21]:
a = torch.from_numpy(n)

In [22]:
a

tensor([[ 1.4779, -0.2952, -1.4490],
        [-0.1110,  0.3654, -1.1198]], dtype=torch.float64)

In [24]:
a.numpy()

array([[ 1.47794424, -0.29524533, -1.44897026],
       [-0.11100034,  0.3654316 , -1.11984385]])

In [23]:
import tensorflow as tf

In [25]:
t = tf.constant(a)

In [26]:
t

<tf.Tensor: shape=(2, 3), dtype=float64, numpy=
array([[ 1.47794424, -0.29524533, -1.44897026],
       [-0.11100034,  0.3654316 , -1.11984385]])>

In [27]:
t.numpy()

array([[ 1.47794424, -0.29524533, -1.44897026],
       [-0.11100034,  0.3654316 , -1.11984385]])

# 张量运算

In [28]:
# tensor运算规则和numpy的ndarray很像
# 和单个数字运算
t = torch.ones(2, 3)
t

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [29]:
t + 3

tensor([[4., 4., 4.],
        [4., 4., 4.]])

In [30]:
torch.add(t, 3)

tensor([[4., 4., 4.],
        [4., 4., 4.]])

In [31]:
x1 = torch.ones(2, 3)

In [32]:
# 对应位置的元素相加, element-wise操作 残差网络的+ 就是element-wise相加
x1 + t

tensor([[2., 2., 2.],
        [2., 2., 2.]])

In [33]:
# 有输出不会改变原始值
t.add(x1)

tensor([[2., 2., 2.],
        [2., 2., 2.]])

In [34]:
t

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [35]:
# 如果想改变原始值. pytorch中带下划线的操作会改变原始值.
t.add_(x1)

tensor([[2., 2., 2.],
        [2., 2., 2.]])

In [36]:
t

tensor([[2., 2., 2.],
        [2., 2., 2.]])

In [39]:
b = torch.ones(3, 3)
torch.inverse(b)

_LinAlgError: torch.linalg.inv: The diagonal element 2 is zero, the inversion could not be completed because the input matrix is singular.

In [40]:
# 改变tensor的形状
t.reshape(3, 2)

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])

In [41]:
t.view(3,2)

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])

In [42]:
# 聚合操作
t.mean()

tensor(2.)

In [43]:
t.sum()

tensor(12.)

In [44]:
# 指定维度进行聚合, 不写维度, 默认会把所有维度聚合掉.
# dimension axis
x = t.sum(dim=1)

In [45]:
x

tensor([6., 6.])

In [46]:
x = x.sum()

In [47]:
x

tensor(12.)

In [48]:
# 一个数字叫做scalars(标量), 带中括号的数据较做向量
# item是专门用来取出tensor中的标量的值
x.item()

12.0

取值

In [49]:
x = torch.randn(3, 4)
x

tensor([[ 0.4315, -0.8709,  1.0485, -0.3349],
        [ 0.8269,  0.4150, -1.2512,  0.5627],
        [ 1.5769, -0.0017, -1.5612, -0.0688]])

In [50]:
x[0]

tensor([ 0.4315, -0.8709,  1.0485, -0.3349])

In [51]:
x[0, 0]

tensor(0.4315)

In [52]:
# tensor的切片和索引操作和ndarray是完全一样.
x[0, :3]

tensor([ 0.4315, -0.8709,  1.0485])

In [53]:
x = torch.rand(32, 224, 224, 3)

In [54]:
x[0,:,:,0]

tensor([[0.1127, 0.4634, 0.4486,  ..., 0.4566, 0.6134, 0.7103],
        [0.7561, 0.2857, 0.0208,  ..., 0.9945, 0.3100, 0.7738],
        [0.2251, 0.2040, 0.3941,  ..., 0.8831, 0.9920, 0.4289],
        ...,
        [0.6964, 0.2720, 0.1280,  ..., 0.6644, 0.7808, 0.1286],
        [0.1947, 0.9066, 0.1069,  ..., 0.9600, 0.4110, 0.9072],
        [0.3164, 0.9479, 0.3928,  ..., 0.3168, 0.7480, 0.4652]])

In [55]:
x[0,:,:,0].shape

torch.Size([224, 224])

In [56]:
# 矩阵乘法
a1 = torch.randn(2, 3)
a2 = torch.randn(3, 5)
torch.matmul(a1, a2)

tensor([[ 0.6653, -0.4558,  2.9684, -1.8499,  1.0966],
        [-1.1719, -1.3297,  0.1182, -0.0808,  1.1179]])

In [57]:
# @也是矩阵点乘的快捷写法
a1 @ a2

tensor([[ 0.6653, -0.4558,  2.9684, -1.8499,  1.0966],
        [-1.1719, -1.3297,  0.1182, -0.0808,  1.1179]])

In [58]:
# pytorch中的dot是向量的乘法, 必须是一维向量. 
a1.dot(a2)

RuntimeError: 1D tensors expected, but got 2D and 2D tensors

In [59]:
x1 = torch.rand(5)
x2 = torch.rand(5)
print(x1, x2)
x1.dot(x2)

tensor([0.7099, 0.1338, 0.5663, 0.8701, 0.8770]) tensor([0.4485, 0.4817, 0.9051, 0.9737, 0.0407])


tensor(1.7783)

In [60]:
(x1*x2).sum()

tensor(1.7783)

# 张量的自动微分

In [61]:
# 说白了就是自动求导.
# 在要求导的变量定义中加上requires_grad=True表示要追踪这个变量的导数
x = torch.ones(2, 2, requires_grad=True)
y = 2 * x + 2

In [62]:
y

tensor([[4., 4.],
        [4., 4.]], grad_fn=<AddBackward0>)

In [63]:
x.requires_grad

True

In [64]:
x2 = torch.ones(2, 2)

In [65]:
# 默认是不会自动求导.
x2.requires_grad

False

In [66]:
y.grad_fn

In [67]:
# 导数必须由标量输出创建.意思就说你要求的最后结果, 必须是一个标量. 不能是向量. 
# 导数的定义中要求是对某一点求导. 
y.backward()

RuntimeError: grad can be implicitly created only for scalar outputs

In [68]:
z = y.mean()

In [69]:
# 只有执行完backward之后, 所有requires_grad=True的变量的导数都会被自动求出. 
z.backward()

In [70]:
x.grad

tensor([[0.5000, 0.5000],
        [0.5000, 0.5000]])

In [71]:
z = y * y * 3
out = z.mean()

In [72]:
out

tensor(48., grad_fn=<MeanBackward0>)

In [73]:
out.backward()

RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.

In [74]:
y.grad

C:\ProgramData\Anaconda3\lib\site-packages\torch\_tensor.py:1104: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at  C:\cb\pytorch_1000000000000\work\build\aten\src\ATen/core/TensorBody.h:475.)
  return self._grad


In [75]:
# 求非叶子节点的tensor的导数, 必须使用retain_grad, 不然会报警告. 
y.retain_grad

<function Tensor.retain_grad>

In [76]:
# 如果不需要求导, 可以把代码包在torch.no_grad()中
x.requires_grad

True

In [77]:
(x ** 2).requires_grad

True

In [78]:
# 通过with torch.no_grad() 暂时不对x求导
with torch.no_grad():
    print((x ** 2).requires_grad)

False


In [79]:
x.requires_grad

True

In [80]:
y = x ** 2 + 2
y.requires_grad

True

In [81]:
y.detach()

tensor([[3., 3.],
        [3., 3.]])

In [82]:
y.requires_grad

True

In [83]:
x.detach()

tensor([[1., 1.],
        [1., 1.]])

In [84]:
y = x.detach()

In [85]:
y.requires_grad

False

In [86]:
# 除了在定义变量的时候指定requires_grad,也可以通过requires_grad_()方法修改变量的requires_grad属性
a = torch.randn(2, 2)
a = a * 3 + 2
print(a.requires_grad)

False


In [87]:
# 加了下划线, 会直接修改原始数据.
a.requires_grad_(True)

tensor([[6.8397, 1.3765],
        [3.0723, 2.3427]], requires_grad=True)

In [88]:
print(a.requires_grad)

True
