In [1]:
import torch 
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# 读取数据

In [2]:
data = pd.read_csv(r'C:/Users/Administrator/Desktop/data/deep_learning/dataset./credit-a.csv', header=None)

In [3]:
data.head()

0      1      2   3   4   5   6     7   8   9   10  11  12   13     14  15
0   0  30.83  0.000   0   0   9   0  1.25   0   0   1   1   0  202    0.0  -1
1   1  58.67  4.460   0   0   8   1  3.04   0   0   6   1   0   43  560.0  -1
2   1  24.50  0.500   0   0   8   1  1.50   0   1   0   1   0  280  824.0  -1
3   0  27.83  1.540   0   0   9   0  3.75   0   0   5   0   0  100    3.0  -1
4   0  20.17  5.625   0   0   9   0  1.71   0   1   0   1   2  120    0.0  -1

In [4]:
# 前15列是特征, 最后一列是标记
X = data.iloc[:, :-1]
X.shape

(653, 15)

In [5]:
Y = data.iloc[:, -1]

In [6]:
# series是不能做为标记
Y

0     -1
1     -1
2     -1
3     -1
4     -1
      ..
648    1
649    1
650    1
651    1
652    1
Name: 15, Length: 653, dtype: int64

# 数据预处理

In [7]:
# 把标记变成0和1, 方便最后求概率
Y.replace(-1, 0, inplace=True)

In [8]:
Y.value_counts()

1    357
0    296
Name: 15, dtype: int64

In [10]:
data.info

<bound method DataFrame.info of      0      1       2   3   4   5   6     7   8   9   10  11  12   13     14  \
0     0  30.83   0.000   0   0   9   0  1.25   0   0   1   1   0  202    0.0   
1     1  58.67   4.460   0   0   8   1  3.04   0   0   6   1   0   43  560.0   
2     1  24.50   0.500   0   0   8   1  1.50   0   1   0   1   0  280  824.0   
3     0  27.83   1.540   0   0   9   0  3.75   0   0   5   0   0  100    3.0   
4     0  20.17   5.625   0   0   9   0  1.71   0   1   0   1   2  120    0.0   
..   ..    ...     ...  ..  ..  ..  ..   ...  ..  ..  ..  ..  ..  ...    ...   
648   0  21.08  10.085   1   1  11   1  1.25   1   1   0   1   0  260    0.0   
649   1  22.67   0.750   0   0   0   0  2.00   1   0   2   0   0  200  394.0   
650   1  25.25  13.500   1   1  13   7  2.00   1   0   1   0   0  200    1.0   
651   0  17.92   0.205   0   0  12   0  0.04   1   1   0   1   0  280  750.0   
652   0  35.00   3.375   0   0   0   1  8.29   1   1   0   0   0    0    0.0   

     15

In [11]:
data.describe()

0           1           2           3           4           5   \
count  653.000000  653.000000  653.000000  653.000000  653.000000  653.000000   
mean     0.310873   31.503813    4.829533    0.238897    0.238897    5.918836   
std      0.463206   11.838267    5.027077    0.433866    0.433866    4.469511   
min      0.000000   13.750000    0.000000    0.000000    0.000000    0.000000   
25%      0.000000   22.580000    1.040000    0.000000    0.000000    2.000000   
50%      0.000000   28.420000    2.835000    0.000000    0.000000    6.000000   
75%      1.000000   38.250000    7.500000    0.000000    0.000000    9.000000   
max      1.000000   76.750000   28.000000    2.000000    2.000000   13.000000   

               6           7           8           9           10          11  \
count  653.000000  653.000000  653.000000  653.000000  653.000000  653.000000   
mean     1.153139    2.244296    0.465544    0.560490    2.502297    0.537519   
std      2.074785    3.371120    0.499194    0.496708    4.968497    0.498973   
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
25%      0.000000    0.165000    0.000000    0.000000    0.000000    0.000000   
50%      0.000000    1.000000    0.000000    1.000000    0.000000    1.000000   
75%      1.000000    2.625000    1.000000    1.000000    3.000000    1.000000   
max      8.000000   28.500000    1.000000    1.000000   67.000000    1.000000   

               12           13             14          15  
count  653.000000   653.000000     653.000000  653.000000  
mean     0.165391   180.359877    1013.761103    0.546708  
std      0.548475   168.296811    5253.278504    0.498195  
min      0.000000     0.000000       0.000000    0.000000  
25%      0.000000    73.000000       0.000000    0.000000  
50%      0.000000   160.000000       5.000000    1.000000  
75%      0.000000   272.000000     400.000000    1.000000  
max      2.000000  2000.000000  100000.000000    1.000000

# 构建网络

In [9]:
X = torch.from_numpy(X.values).type(torch.FloatTensor)
Y = torch.from_numpy(Y.values.reshape(-1, 1)).type(torch.FloatTensor)

In [12]:
# 回归和分类之间, 区别其实不大. 回归后面加上一层sigmoid, 就变成分类了.
from torch import nn

In [15]:
model = nn.Sequential(
    nn.Linear(15, 1024),
    nn.Linear(1024, 256),
    nn.Linear(256,1),
    nn.Sigmoid()
)

In [16]:
model

Sequential(
  (0): Linear(in_features=15, out_features=1024, bias=True)
  (1): Linear(in_features=1024, out_features=256, bias=True)
  (2): Linear(in_features=256, out_features=1, bias=True)
  (3): Sigmoid()
)

In [17]:
# BCE binary cross entroy 二分类的交叉熵损失
loss_fn = nn.BCELoss()

In [18]:
opt = torch.optim.SGD(model.parameters(), lr=0.0001)

In [19]:
X.shape

torch.Size([653, 15])

In [20]:
batch_size = 32
steps = 653 // 32

In [21]:
steps

20

In [22]:
for epoch in range(1000):
    # 每次取32个数据
    for batch in range(steps):
        # 起始索引
        start = batch * batch_size
        # 结束索引
        end = start + batch_size
        # 取数据
        x = X[start: end]
        y = Y[start: end]
        y_pred = model(x)
        loss = loss_fn(y_pred, y)
        # 梯度清零
        opt.zero_grad()
        # 反向传播
        loss.backward()
        # 更新
        opt.step()

In [23]:
model.state_dict()

OrderedDict([('0.weight',
              tensor([[-0.0056,  0.0072, -0.2440,  ...,  0.0242, -0.1029, -0.1316],
                      [ 0.0279, -0.0257, -0.1807,  ..., -0.0095, -0.2474, -0.1488],
                      [ 0.0575, -0.2496,  0.1073,  ...,  0.1516, -0.2257,  0.1775],
                      ...,
                      [ 0.1304, -0.0570,  0.2359,  ...,  0.1532,  0.1478, -0.0923],
                      [ 0.0754, -0.0132, -0.0339,  ..., -0.2106,  0.2039,  0.2098],
                      [-0.0281, -0.1202, -0.0444,  ..., -0.0785,  0.0973, -0.1198]])),
             ('0.bias',
              tensor([-0.1546, -0.1128,  0.2453,  ..., -0.0852,  0.0861,  0.2407])),
             ('1.weight',
              tensor([[-0.0061, -0.0344,  0.0195,  ..., -0.0156,  0.0120, -0.0015],
                      [ 0.0226, -0.0215, -0.0040,  ...,  0.0006, -0.0110,  0.0228],
                      [-0.0298, -0.0165,  0.0296,  ...,  0.0133,  0.0280, -0.0102],
                      ...,
                      [ 0.

In [24]:
# 计算正确率
# 设定阈值
# 现在预测得到的是概率. 我们根据阈值, 把概率转化为类别, 就可以计算准确率. 
((model(X).data.numpy() > 0.5) == Y.numpy()).mean()

0.7366003062787136