In [2]:
# Dataset: __len__, __getitem__都可以成为Dataset

In [3]:
# dataset[0] = dataset.__getitem__[0]

In [4]:
import torch
import numpy as np
from torchvision import transforms
import torch.nn as nn
import torch.nn.functional as F

In [5]:
import glob

In [6]:
from PIL import Image

In [7]:
all_img_path = glob.glob(r'D:\AIoT-深度学习视频版\深度学习基础\day56_dropout和bn\代码\dataset\*.jpg')

In [8]:
all_img_path[:5]

['D:\\AIoT-深度学习视频版\\深度学习基础\\day56_dropout和bn\\代码\\dataset\\cloudy1.jpg',
 'D:\\AIoT-深度学习视频版\\深度学习基础\\day56_dropout和bn\\代码\\dataset\\cloudy10.jpg',
 'D:\\AIoT-深度学习视频版\\深度学习基础\\day56_dropout和bn\\代码\\dataset\\cloudy100.jpg',
 'D:\\AIoT-深度学习视频版\\深度学习基础\\day56_dropout和bn\\代码\\dataset\\cloudy101.jpg',
 'D:\\AIoT-深度学习视频版\\深度学习基础\\day56_dropout和bn\\代码\\dataset\\cloudy102.jpg']

In [9]:
# 建立类别和索引之间的映射关系
species = ['cloudy', 'rain', 'shine', 'sunrise']

In [10]:
species_to_idx = dict((c, i) for i, c in enumerate(species))

In [11]:
species_to_idx

{'cloudy': 0, 'rain': 1, 'shine': 2, 'sunrise': 3}

In [12]:
# 调换一下key和value的顺序
idx_to_species = dict((v, k) for k, v in species_to_idx.items())

In [13]:
idx_to_species

{0: 'cloudy', 1: 'rain', 2: 'shine', 3: 'sunrise'}

In [14]:
'cloudy' in all_img_path[0]

True

In [15]:
# 生成所有图片的label
all_labels = []

for img in all_img_path:
    for i, c in enumerate(species):
        if c in img:
            all_labels.append(i)

In [16]:
all_img_path[:5]

['D:\\AIoT-深度学习视频版\\深度学习基础\\day56_dropout和bn\\代码\\dataset\\cloudy1.jpg',
 'D:\\AIoT-深度学习视频版\\深度学习基础\\day56_dropout和bn\\代码\\dataset\\cloudy10.jpg',
 'D:\\AIoT-深度学习视频版\\深度学习基础\\day56_dropout和bn\\代码\\dataset\\cloudy100.jpg',
 'D:\\AIoT-深度学习视频版\\深度学习基础\\day56_dropout和bn\\代码\\dataset\\cloudy101.jpg',
 'D:\\AIoT-深度学习视频版\\深度学习基础\\day56_dropout和bn\\代码\\dataset\\cloudy102.jpg']

In [17]:
all_labels[:5]

[0, 0, 0, 0, 0]

In [18]:
all_img_path

['D:\\AIoT-深度学习视频版\\深度学习基础\\day56_dropout和bn\\代码\\dataset\\cloudy1.jpg',
 'D:\\AIoT-深度学习视频版\\深度学习基础\\day56_dropout和bn\\代码\\dataset\\cloudy10.jpg',
 'D:\\AIoT-深度学习视频版\\深度学习基础\\day56_dropout和bn\\代码\\dataset\\cloudy100.jpg',
 'D:\\AIoT-深度学习视频版\\深度学习基础\\day56_dropout和bn\\代码\\dataset\\cloudy101.jpg',
 'D:\\AIoT-深度学习视频版\\深度学习基础\\day56_dropout和bn\\代码\\dataset\\cloudy102.jpg',
 'D:\\AIoT-深度学习视频版\\深度学习基础\\day56_dropout和bn\\代码\\dataset\\cloudy103.jpg',
 'D:\\AIoT-深度学习视频版\\深度学习基础\\day56_dropout和bn\\代码\\dataset\\cloudy104.jpg',
 'D:\\AIoT-深度学习视频版\\深度学习基础\\day56_dropout和bn\\代码\\dataset\\cloudy105.jpg',
 'D:\\AIoT-深度学习视频版\\深度学习基础\\day56_dropout和bn\\代码\\dataset\\cloudy106.jpg',
 'D:\\AIoT-深度学习视频版\\深度学习基础\\day56_dropout和bn\\代码\\dataset\\cloudy107.jpg',
 'D:\\AIoT-深度学习视频版\\深度学习基础\\day56_dropout和bn\\代码\\dataset\\cloudy108.jpg',
 'D:\\AIoT-深度学习视频版\\深度学习基础\\day56_dropout和bn\\代码\\dataset\\cloudy109.jpg',
 'D:\\AIoT-深度学习视频版\\深度学习基础\\day56_dropout和bn\\代码\\dataset\\cloudy11.jpg',
 'D:\\AIoT-深度学习视频版\\深度学习基础\\d

In [19]:
# 借助ndarray的索引取值的方法, 打乱数据
index = np.random.permutation(len(all_img_path))

In [20]:
all_img_path = np.array(all_img_path)[index]

In [21]:
all_labels = np.array(all_labels)[index]

In [22]:
all_img_path[:5]

array(['D:\\AIoT-深度学习视频版\\深度学习基础\\day56_dropout和bn\\代码\\dataset\\cloudy192.jpg',
       'D:\\AIoT-深度学习视频版\\深度学习基础\\day56_dropout和bn\\代码\\dataset\\sunrise260.jpg',
       'D:\\AIoT-深度学习视频版\\深度学习基础\\day56_dropout和bn\\代码\\dataset\\rain164.jpg',
       'D:\\AIoT-深度学习视频版\\深度学习基础\\day56_dropout和bn\\代码\\dataset\\sunrise296.jpg',
       'D:\\AIoT-深度学习视频版\\深度学习基础\\day56_dropout和bn\\代码\\dataset\\sunrise228.jpg'],
      dtype='<U65')

In [23]:
all_labels[:5]

array([0, 3, 1, 3, 3])

In [24]:
idx_to_species

{0: 'cloudy', 1: 'rain', 2: 'shine', 3: 'sunrise'}

In [25]:
# 手动的划分一下训练数据和测试数据
split = int(len(all_img_path) * 0.8)

In [26]:
train_imgs = all_img_path[:split]
train_labels = all_labels[:split]

test_imgs = all_img_path[split:]
test_labels = all_labels[split:]

In [34]:
train_labels

array([0, 3, 1, 3, 3, 3, 0, 3, 3, 3, 2, 2, 2, 0, 3, 2, 0, 2, 0, 0, 2, 0,
       1, 1, 1, 2, 2, 2, 2, 3, 2, 0, 1, 2, 2, 0, 1, 1, 3, 1, 1, 3, 2, 1,
       3, 0, 2, 0, 1, 3, 3, 0, 3, 3, 1, 3, 3, 1, 2, 0, 2, 2, 3, 3, 1, 3,
       3, 0, 3, 0, 1, 3, 0, 0, 1, 0, 3, 3, 2, 2, 1, 3, 0, 3, 0, 3, 0, 1,
       1, 3, 0, 2, 0, 3, 3, 0, 3, 3, 0, 2, 0, 2, 2, 2, 3, 2, 3, 3, 3, 1,
       0, 1, 1, 2, 2, 3, 3, 0, 3, 1, 0, 0, 3, 3, 2, 3, 3, 1, 1, 3, 3, 2,
       0, 3, 0, 2, 2, 0, 0, 1, 1, 2, 0, 1, 3, 3, 1, 0, 2, 1, 0, 0, 2, 1,
       3, 2, 2, 1, 1, 1, 2, 3, 0, 2, 3, 1, 0, 1, 2, 0, 3, 0, 0, 0, 0, 3,
       1, 0, 0, 2, 2, 1, 2, 3, 0, 1, 0, 1, 2, 3, 3, 2, 3, 3, 0, 3, 2, 1,
       3, 3, 3, 1, 1, 2, 2, 1, 0, 1, 2, 3, 1, 3, 0, 0, 0, 1, 0, 3, 1, 2,
       3, 0, 2, 0, 3, 3, 3, 2, 0, 1, 3, 3, 0, 2, 2, 3, 0, 3, 0, 1, 2, 3,
       1, 3, 2, 2, 2, 0, 2, 0, 1, 3, 2, 2, 0, 3, 0, 0, 0, 3, 2, 3, 3, 1,
       0, 1, 0, 3, 1, 3, 0, 0, 2, 3, 1, 3, 3, 3, 1, 1, 0, 2, 2, 0, 2, 1,
       2, 2, 0, 1, 3, 1, 3, 1, 1, 1, 0, 1, 3, 2, 0,

In [27]:
transform = transforms.Compose([
    transforms.Resize((96, 96)),
    transforms.ToTensor()
])

In [42]:
class MyDataset(torch.utils.data.Dataset):
    def __init__(self, img_paths, labels, transform):
        # 调用父类的init这里可以不写. 
#         super().__init__()
        self.imgs = img_paths
        self.labels = labels
        self.transforms = transform
        
    def __getitem__(self, index):
        # 根据index获取item
        img_path = self.imgs[index]
        label = self.labels[index]
        
        print(index)
        # 通过PIL的Image读取图片. 
        img = Image.open(img_path)
        data = self.transforms(img)
        print(label)
        print(type(label))
        return data, torch.from_numpy(label).type(torch.LongTensor)
    
    def __len__(self):
        return len(self.imgs)

In [40]:
dataset = MyDataset(all_img_path, all_labels, transform)

In [30]:
len(dataset)

1122

In [41]:
imgs, labels = next(iter(dataset))

0
<class 'numpy.int32'>


TypeError: expected np.ndarray (got numpy.int32)

In [33]:
all_labels

array([0, 3, 1, ..., 2, 3, 2])

In [43]:
train_ds = MyDataset(train_imgs, train_labels, transform)
test_ds = MyDataset(test_imgs, test_labels, transform)


train_dl = torch.utils.data.DataLoader(train_ds, batch_size=16, shuffle=True)
test_dl = torch.utils.data.DataLoader(test_ds, batch_size=16 * 2)


In [44]:
imgs, labels = next(iter(train_dl))

189
3
<class 'numpy.int32'>


TypeError: expected np.ndarray (got numpy.int32)

In [ ]:
imgs.shape

In [ ]:
labels

In [ ]:
# 添加BN层.
# 定义模型
class Net(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = nn.Conv2d(3, 16, 3)   # 16 * 94 * 94
        self.bn1 = nn.BatchNorm2d(16)
        self.pool = nn.MaxPool2d(2, 2)     # 16 * 47 * 47
        
        self.conv2 = nn.Conv2d(16, 32, 3)  # 32 * 45 * 45  -> pooling -> 32 * 22 * 22
        self.bn2 = nn.BatchNorm2d(32)
        self.conv3 = nn.Conv2d(32, 64, 3)  # 64 * 20 * 20  -> pooling -> 64 * 10 * 10
        self.bn3 = nn.BatchNorm2d(64)
        self.dropout = nn.Dropout()
        
        # batch , channel, height, width, 64, 
        self.fc1 = nn.Linear(64 * 10 * 10, 1024)
        self.bn_fc1 = nn.BatchNorm1d(1024)
        self.fc2 = nn.Linear(1024, 256)
        self.bn_fc2 = nn.BatchNorm1d(256)
        self.fc3 = nn.Linear(256, 4)
        
    def forward(self, x):
        x = self.pool(F.relu(self.conv1(x)))
        x = self.bn1(x)
        x = self.pool(F.relu(self.conv2(x)))
        x = self.bn2(x)
        x = self.pool(F.relu(self.conv3(x)))
        x = self.bn3(x)
        # x.view(-1, 64 * 10 * 10)
        x = nn.Flatten()(x)
        x = F.relu(self.fc1(x))
        x = self.bn_fc1(x)
        x = self.dropout(x)
        x = F.relu(self.fc2(x))
        x = self.bn_fc2(x)
        x = self.dropout(x)
        x = self.fc3(x)
        return x

In [ ]:
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')

In [ ]:
model = Net()
# 把model拷到gpu上
if torch.cuda.is_available():
    model.to(device)
    
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)
loss_fn = nn.CrossEntropyLoss()


In [ ]:
def fit(epoch, model, train_loader, test_loader):
    correct = 0
    total = 0
    running_loss = 0
    
    # 因为bn和dropout需要手动指定训练模式和推理模式
    model.train()
    for x, y in train_loader:
        # 把数据放到GPU上去. 
        x, y = x.to(device), y.to(device)
        y_pred = model(x)
        loss = loss_fn(y_pred, y)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        
        with torch.no_grad():
            y_pred = torch.argmax(y_pred, dim=1)
            correct += (y_pred == y).sum().item()
            total += y.size(0)
            running_loss += loss.item()
            
    epoch_loss = running_loss / len(train_loader.dataset)
    epoch_acc = correct / total
        
    # 测试过程
    test_correct = 0
    test_total = 0
    test_running_loss = 0
    model.eval()
    with torch.no_grad():
        for x, y in test_loader:
            x, y = x.to(device), y.to(device)
            y_pred = model(x)
            loss = loss_fn(y_pred, y)
            y_pred = torch.argmax(y_pred, dim=1)
            test_correct += (y_pred == y).sum().item()
            test_total += y.size(0)
            test_running_loss += loss.item()
    test_epoch_loss = test_running_loss / len(test_loader.dataset)
    test_epoch_acc = test_correct / test_total

    print('epoch: ', epoch,
         'loss: ', round(epoch_loss, 3),
         'accuracy: ', round(epoch_acc, 3),
         'test_loss: ', round(test_epoch_loss, 3),
         'test_accuracy: ', round(test_epoch_acc, 3))
    return epoch_loss, epoch_acc, test_epoch_loss, test_epoch_acc

In [ ]:
epochs = 20
train_loss = []
train_acc = []
test_loss = []
test_acc = []
for epoch in range(epochs):
    epoch_loss, epoch_acc, test_epoch_loss, test_epoch_acc = fit(epoch, model, train_dl, test_dl)
    train_loss.append(epoch_loss)
    train_acc.append(epoch_acc)
    
    test_loss.append(epoch_loss)
    test_acc.append(epoch_acc)

In [ ]:
all_labels.dtype